import Layout from '@/components/layout';
import { useStateContext } from '@/context/ContextProvider';
import { Box, Card } from '@mui/material';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { HiUser } from 'react-icons/hi';
import { GoLocation } from 'react-icons/go';
import { BsTelephone } from 'react-icons/bs';
import Head from 'next/head';

const OrderPage = () => {
  const { query } = useRouter();
  const { order } = query;
  const { orders } = useStateContext();

  const theOrder = orders.find((x) => x.customerName == order);
  console.log(orders);
  return (
    <Layout>
      <Head>
        <title>{`${order} | Arzu`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" ml-4 mt-4">
        <Link href={'/adminOrders'}>
          <button className="space-x-1 items-center mb-4 flex border border-solid font-poppins border-neutral-700 px-2 hover:bg-neutral-700 hover:text-white">
            Back to Orders
          </button>
        </Link>

        <div className="flex tracking-wide text-2xl font-poppins space-x-2">
          <p className="font-semibold ">Invoice number :</p>
          <p> {theOrder?.invoiceNumber}</p>
        </div>
        <div className=" flex font-poppins text-xl space-x-2 tracking-wide">
          <p className="font-semibold ">Status:</p>
          <p>{theOrder?.shipped ? 'Shipped' : 'Not Shipped'}</p>
        </div>
        <div className=" flex font-poppins text-xl space-x-2 tracking-wide">
          <p className="font-semibold ">Order Date:</p>
          <p>{theOrder?.date.slice(0, 10)}</p>
        </div>
        <div className=" flex font-poppins text-xl space-x-2 tracking-wide">
          <p className="font-semibold ">Order Time:</p>
          <p>{theOrder?.date.slice(11, 16)}</p>
        </div>
        <div className=" space-y-4 mb-8">
          <Card className="mt-4">
            <Box sx={{ minWidth: 400 }}>
              <div>
                {theOrder?.items.map((item, i) => (
                  <div
                    key={i}
                    className=" flex font-poppins justify-between mb-2 pr-4 items-center"
                  >
                    <img width={100} height={100} src={item.thumbnail?.url} />
                    <div>
                      <p>{item.title}</p>
                    </div>
                    <div>
                      <p>Quantity: {item.cartQuantity}</p>
                      <p>Size: {item.size}</p>
                    </div>
                  </div>
                ))}
                <div className="flex justify-center font-poppins text-xl  pb-4 space-x-2">
                  <p className="font-semibold">Subtotal: </p>
                  <p> {theOrder?.subtotal} EGP </p>
                </div>
              </div>
            </Box>
          </Card>
          <Card>
            <Box sx={{ minWidth: 400 }}>
              <div className=" mt-4">
                <p className="font-bold font-poppins text-center text-3xl ">
                  Customer Details
                </p>
                <div className=" text-lg font-poppins space-y-4 p-4">
                  <div className="flex space-x-4">
                    <span>
                      <HiUser size={24} />
                    </span>
                    <p>{theOrder?.customerName}</p>
                  </div>
                  <div className=" flex space-x-4">
                    <span>
                      <GoLocation size={24} />
                    </span>
                    <p>{theOrder?.address}</p>
                  </div>
                  <div className=" flex space-x-4">
                    <span>
                      <BsTelephone size={24} />
                    </span>
                    <p>{theOrder?.phone}</p>
                  </div>
                </div>
              </div>
            </Box>
          </Card>
        </div>
      </div>
    </Layout>
  );
};

export default OrderPage;
