import CheckoutWizard from '@/components/checkoutWizard';
import { selectItems, selectTotal } from '@/slices/bagSlice';
import { useState } from 'react';
import { useSelector } from 'react-redux';
import axios from './api/axios';
import Head from 'next/head';
import NavBar from '@/components/nav';
import DropDown from '@/components/dropDown';
import dynamic from 'next/dynamic';

const Checkout = () => {
  const items = useSelector(selectItems);

  const [customerName, setCustomerName] = useState('');
  const [gov, setGov] = useState('');
  const [city, setCity] = useState('');
  const [add, setAdd] = useState('');
  const [phone, setPhone] = useState('');
  const [phoneTwo, setPhoneTwo] = useState('');
  const [email, setEmail] = useState('');
  const subtotal = useSelector(selectTotal);
  const address = add + ',' + city + ',' + gov;

  const [visible, setVisible] = useState(false);
  const showBar = () => setVisible(!visible);

  const handleSubmit = async () => {
    try {
      const response = await axios.post('/newOrder', {
        customerName,
        phone,
        phoneTwo,
        email,
        address,
        items,
        subtotal,
      });
      console.log(response);
    } catch (error) {
      console.log(error);
    }
  };
  return (
    <>
      <Head>
        <title>{'Checkout | Arzu'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div className=" fixed top-0 z-10 w-full">
          <NavBar showBar={showBar} />
        </div>
        {visible ? (
          <div className=" fixed overscroll-contain bg-opacity-80 bg-white h-screen  top-0 z-20 min-w-full">
            <DropDown showBar={showBar} />
          </div>
        ) : (
          <></>
        )}
        <div className="my-12">
          <div>
            <CheckoutWizard activeStep={1} />
          </div>
        </div>
        <div className="md:grid md:grid-cols-5 ">
          <form
            onSubmit={handleSubmit}
            className="border md:col-span-3 mx-5 shadow-md p-2 "
          >
            <div className="ml-2">
              <label>Full Name :</label>
              <span className="text-red-500"> *</span>
              <br />
              <input
                className="border mb-2"
                type="text"
                onChange={(e) => setCustomerName(e.target.value)}
              />
              <br />
              <label>Governorate :</label>
              <span className="text-red-500"> *</span>
              <br />
              <input
                className="border mb-2"
                type="text"
                onChange={(e) => setGov(e.target.value)}
              />
              <br />
              <label>City :</label>
              <span className="text-red-500"> *</span>
              <br />
              <input
                className="border mb-2"
                type="text"
                onChange={(e) => setCity(e.target.value)}
              />
              <br />
              <label>Address :</label>
              <span className="text-red-500"> *</span>
              <br />
              <input
                className="border mb-2"
                type="text"
                onChange={(e) => setAdd(e.target.value)}
              />
              <br />
              <label>Phone Number :</label>
              <span className="text-red-500"> *</span>
              <br />
              <input
                className="border mb-2"
                type="text"
                onChange={(e) => setPhone(e.target.value)}
              />
              <br />
              <label>Another Phone Number :</label>
              <br />
              <input
                className="border mb-2"
                type="text"
                onChange={(e) => setPhoneTwo(e.target.value)}
              />
              <br />
              <label>Email address :</label>
              <br />
              <input
                className="border mb-2"
                type="text"
                onChange={(e) => setEmail(e.target.value)}
              />
            </div>

            <div className="ml-2 my-3">
              <button className=" flex border border-solid font-poppins border-neutral-700 px-2 hover:bg-neutral-700 hover:text-white">
                Confirm Order
              </button>
            </div>
          </form>
        </div>
      </div>
    </>
  );
};

export default dynamic(() => Promise.resolve(Checkout), { ssr: false });
