import CheckoutWizard from '@/components/checkoutWizard';
import MainLayout from '@/components/mainLayout';
import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import { FiArrowLeft } from 'react-icons/fi';

const Confirmed = () => {
  return (
    <>
      <Head>
        <title>{'Confirmed | Arzu'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div className="mt-14">
          <CheckoutWizard activeStep={2} />
        </div>

        <div className=" text-center text-3xl font-poppins font-semibold">
          <h1>Your Order is going to reach you within 3 Working Days</h1>
        </div>

        <Link href={'/'}>
          <div className="p-4 mx-auto">
            <button className=" flex border border-solid font-poppins border-neutral-700 px-2 hover:bg-neutral-700 hover:text-white">
              <span className=" pt-1 px-1">
                <FiArrowLeft size={14} />
              </span>{' '}
              CONTINUE SHOPPING
            </button>
          </div>
        </Link>
      </MainLayout>
    </>
  );
};

export default Confirmed;
