import Carousels from '@/components/carousels';
import CategorySection from '@/components/categorySection';
import DropDown from '@/components/dropDown';
import Footer from '@/components/footer';
import NavBar from '@/components/nav';
import Head from 'next/head';
import { useState, useEffect } from 'react';
import dynamic from 'next/dynamic';
import axios from './api/axios';
import MainLayout from '@/components/mainLayout';

function Home() {
  const [products, setProducts] = useState([]);
  const [categories, setCategories] = useState([]);

  const getAllproducts = async () => {
    const response = await axios.get('/getAllProducts');

    setProducts(response.data);
  };
  useEffect(() => {
    getAllproducts();
  }, []);
  const getCategories = async () => {
    const response = await axios.get('/getCategories');

    setCategories(response.data);
  };
  useEffect(() => {
    getCategories();
  }, []);

  return (
    <>
      <Head>
        <title>{'Arzu'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div className="min-h-screen flex flex-col justify-between">
          <div className=" relative">
            <Carousels />
          </div>
          <CategorySection products={products} categories={categories} />
          <div className="flex justify-center">
            <h1 className=" font-poppins font-semibold text-xl">
              {' '}
              Latest Updates{' '}
            </h1>
          </div>
          <div className="grid grid-cols-2 p-3">
            <div>
              <h4 className="text-xs  font-poppins font-thin">
                {' '}
                Ready for New
              </h4>
              <div className="text-3xl pt-2 space-y-2 font-dmSerif lg:text-8xl">
                <h1>Get into</h1>
                <h1>New Season</h1>
              </div>
              <div className="mt-1">
                <button className="border-2 border-solid border-black text-xs font-poppins font-semibold lg:text-xl">
                  <p className="p-1 ">SHOP ARZU FAVORITES</p>
                </button>
              </div>
            </div>
            <div>
              <img
                src="https://naploungewear.com/wp-content/uploads/2023/01/nap-new-season_1.jpg"
                alt=""
              />
            </div>
          </div>

          <div className="mt-8">
            <Footer />
          </div>
        </div>
      </MainLayout>
    </>
  );
}

export default dynamic(() => Promise.resolve(Home), { ssr: false });
