import DropDown from '@/components/dropDown';
import Footer from '@/components/footer';

import NavBar from '@/components/nav';
import { CardContent } from '@mui/material';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import data from '../../lib/data.json';
import axios from '../api/axios';
import MainLayout from '@/components/mainLayout';

function CategoryPage() {
  const { query } = useRouter();
  const { category } = query;
  const [products, setProducts] = useState([]);
  const getAllproducts = async () => {
    const response = await axios.get('/getAllProducts');

    setProducts(response.data);
  };
  useEffect(() => {
    getAllproducts();
  }, []);
  const catName = products.filter((x) => x.category == category);

  !category ? <div>Category not Found</div> : <></>;
  const [isHovering, setIsHovered] = useState(false);
  const onMouseEnter = (key) => () => setIsHovered({ [key]: true });
  const onMouseLeave = (key) => () => setIsHovered({ [key]: false });

  return (
    <>
      <Head>
        <title>{`${catName.category} | Arzu`}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div className="min-h-screen flex flex-col justify-between">
          <div>
            <div className=" mx-auto max-w-6xl">
              <img
                src="https://img.freepik.com/free-vector/abstract-fashion-monsoon-sale-banner-offer-discount-business-background-free-vector_1340-22458.jpg?w=1480&t=st=1675275161~exp=1675275761~hmac=8b9735f9c9f2fc16c7cb4ff01279f82edcc54157de3682bf66a07aad0d43531a"
                alt=""
              />
            </div>
            <div className="  border-b">
              <h1 className=" text-center font-poppins font-bold pt-2">
                {category}
              </h1>
            </div>

            <div className="grid grid-cols-2 mx-auto max-w-4xl md:grid-cols-3 lg:grid-cols-4">
              {catName.map((product, key) => (
                <div key={key} className="w-full h-full">
                  <CardContent>
                    <Link href={`/product/${product.title}`}>
                      <img
                        onMouseEnter={onMouseEnter(key)}
                        onMouseLeave={onMouseLeave(key)}
                        src={
                          isHovering[key]
                            ? product.images[0]?.url
                            : product.thumbnail.url
                        }
                        alt=""
                      />
                    </Link>

                    <p className=" text-xs text-left font-poppins mt-2">
                      {product.title}
                    </p>
                    <p className=" text-xs font-semibold">
                      EGP {product.price}
                    </p>
                  </CardContent>
                </div>
              ))}
            </div>
          </div>
          <div className="mt-8">
            <Footer />
          </div>
        </div>
      </MainLayout>
    </>
  );
}
export default dynamic(() => Promise.resolve(CategoryPage), { ssr: false });
